### ISSUE TITLE
cowbuilder error creating a base jessie on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by mogray5** [mika/jenkins-debian-glue#130]
Not sure if this is an real issue or if I'm just doing it wrong but jenkins-debian-glue used the below command to try and create a jessie base cowbuilder image on Ubuntu 14.04 LTS

```
sudo DIST=jessie ARCH=amd64 cowbuilder --create --basepath /var/cache/pbuilder/base-jessie-amd64.cow --distribution jessie --debootstrap debootstrap --architecture amd64 --debootstrapopts --arch --debootstrapopts amd64 --debootstrapopts --variant=buildd --configfile=/tmp/tmp.Rdcg5fwTPS --hookdir /usr/share/jenkins-debian-glue/pbuilder-hookdir/
```
This resulted in the below error:

**E: Release signed by unknown key (key id CBF8D6FD518E17E1)**

I resolved it by installing package debian-archive-keyring and then manually running the above command again adding the below debootstrap option:
````
--debootstrapopts --keyring=/usr/share/keyrings/debian-archive-keyring.gpg
````
Awesome tool by the way.

Thanks

**Comment by mika** [comment]
Thanks for your feedback! The commit in https://github.com/mika/jenkins-debian-glue/commit/a4a7b8234ceae896ad0ccede6396a4c69285f319 is supposed to fix this issue, it's untested yet though. If you should have the chance to give this a real-life test I'd very much appreciate that, otherwise I'll test it on my own once I've time and access to a proper test environment again.

**Comment by mogray5** [comment]
Sorry for late notice.  This change did work for me.

I'm now running into the below error which I don't believe is caused by anything jenkins-debian-glue is doing.

```
E: Couldn't download dists/jessie/main/binary-amd64/Packages
E: debootstrap failed
```

Thanks for the change.
