### ISSUE TITLE
Why the need to checkout to a `source` subdirectory?

### ISSUE THREAD

**Issue by tonin** [mika/jenkins-debian-glue#143]
The need to checkout to the `source` subdirectory is preventing some other Jenkins plugins to work as expected.  For example, the [Git Parameter Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Parameter+Plugin) cannot list the existing tags as it doesn't find the local git repo.

There is a simple workaround that just creates a symlink from `source/.git` to `.git` in the workspace root as the start of the *Execute shell* build step.  That is ok, but not ideal.

I'm not sure I understand where this `source/` subdirectory comes from.  Would we be able to eliminate this requirement?

**Comment by mika** [comment]
The checkout to the `source` directory is meant for a clear separation between what's inside the workspace directory for j-d-g and "everything else". We need a reliable way where we can trust the environment, while folks sometimes have the need to place further files in the same workspace directory for processing, execution,...

From my PoV plugins that aren't aware of this property in the Jenkins job are broken, because IIRC that information should be visible to them. The Git Paramter Plugin BTW had further issues like https://issues.jenkins-ci.org/browse/JENKINS-16290 which prevents/prevented its real life usage for me. :-/

I'm afraid we can't really move away from this source subdirectory.

**Comment by tonin** [comment]
Thanks for your answer, I now understand better the reason.  Could be interesting for others to document that at http://jenkins-debian-glue.org/getting_started/manual/ or in the FAQ.
