### ISSUE TITLE
Missing dependency on ruby for lintian-junit-report

### ISSUE THREAD

**Issue by sylvestre** [mika/jenkins-debian-glue#167]
Even if it adds a big dependency for a single script, we should probably depends on ruby or at least suggest it.
Otherwise, it fails with:
```
+ /usr/bin/lintian-junit-report llvm-toolchain-snapshot_4.0~svn290946-1~exp1.dsc
/usr/bin/env: ‘ruby’: No such file or directory
```

**Comment by mika** [comment]
The jenkins-debian-glue-buildenv package provides all the according depends, including the dependency on ruby. Sadly there's no single approach which serves all purposes (due to the way that CI/CD can be very environment specific), I'd recommend to either just install the jenkins-debian-glue-buildenv package (to have all possibly needed dependencies) or deploy tools/packages as needed via configuration management. Do you agree?

**Comment by mika** [comment]
Considering this as resolved, please reopen if you should disagree. Thanks! :)
