### ISSUE TITLE
FQDN need to be correct for automatic setup to work

### ISSUE THREAD

**Issue by arthurlogilab** [mika/jenkins-debian-glue#171]
Following https://jenkins-debian-glue.org/getting_started/automatic/ the jenkins-debian-glue-source job fails if ```hostname -f``` doesn't output something sane (which seems reasonable). 

Either the apply.sh should ensure this is correct or the documentation should mention this. (or is it a problem with the old AMI seen on #170 ?)

**Comment by mika** [comment]
What does `facter fqdn` report for your system? (Because if that's empty we're already aborting, though I'm aware that this might be non-empty and `hostname -f` still fails, though I'd like to see that from your system before implementing a check.)

Executing:

````
if [[ $(facter fqdn) == "" ]] || [[ $(hostname -f 2>/dev/null) == "" ]] ; then     
  echo "Error: please make sure you have a valid FQDN configured in /etc/hosts" >&2
fi
````

would return the Error ... line for you?

**Comment by arthurlogilab** [comment]
```
root@jenkins-debian-glue:~# facter fqdn
jenkins-debian-glue.eu-west-1.compute.internal
root@jenkins-debian-glue:~# hostname -f
hostname: Name or service not known
```

That bit of bash works for me (shows the error).
